{
 "title": "Conductor",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "CONDUCTOR_HOST", "label": "CONDUCTOR_HOST", "query": "http://localhost:5000" }
  ]
 },
 "panels": [
  { "title": "Functional", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Workflows Completed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(workflow_execution_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Workflow Failures",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "workflow_failure_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Workflows Running",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "workflow_running" }
   ]
  },
  {
   "title": "Task Success Rate",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(task_execution_total/2) by (status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tasks Queued",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "last_over_time(task_queue_depth{ownerApp=\"unknown\"}[$__interval])"
    }
   ]
  },
  {
   "title": "Failed Tasks",
   "type": "table",
   "description": "List of all the failed tasks from the very beginning",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "last_over_time(task_execution_seconds_count{status=\"FAILED\"}[$__interval])"
    }
   ]
  },
  {
   "title": "Workflow Runs",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(workflow_execution_total) by (workflowName)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workflows Running",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "workflow_running", "legendFormat": "{{workflowName}}" }
   ]
  },
  {
   "title": "Tasks: Max Time taken",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "task_execution_seconds_max{status=\"COMPLETED\"}"
    }
   ]
  },
  {
   "title": "Tasks: Total Run Times",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (taskType) (task_execution_seconds_sum)"
    }
   ]
  },
  {
   "title": "Task Wait times",
   "type": "timeseries",
   "description": "This indicates the times at which the tasks were waiting in the queue to be picked up for processing by workers",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "task_queue_wait_seconds_max", "legendFormat": "{{taskType}}" }
   ]
  },
  {
   "title": "Task Executions (Max Over Time)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(taskType) (last_over_time(task_execution_seconds_max[$__interval]))",
     "legendFormat": "{{taskType}}"
    }
   ]
  },
  { "title": "Experimental", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Workflow Decision Total Percentile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum by (percentile) (workflow_decision_total)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}