{
 "title": "Conductor Tasks And Workflow Stats",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Select instance",
    "query": "label_values(tasks_in_workflow_count, instance)"
   },
   {
    "name": "workflow",
    "label": "Select workflow",
    "query": "label_values(tasks_in_workflow_count{instance=~\"${instance}\"}, workflowName)"
   }
  ]
 },
 "panels": [
  {
   "title": "Tasks by Instance",
   "type": "table",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (instance)(tasks_in_workflow_count{instance=~\"${instance}\", workflowName=~\"${workflow}\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total executions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 19, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "times" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(tasks_in_workflow_count{instance=~\"${instance}\", workflowName=~\"${workflow}\"})",
     "legendFormat": "{{workflow}}"
    }
   ]
  },
  {
   "title": "Failures by Instance",
   "type": "table",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum by (instance)(workflow_failure_total{instance=~\"${instance}\", workflowName=~\"${workflow}\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total failures",
   "type": "stat",
   "gridPos": { "h": 5, "w": 19, "x": 5, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "times" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(workflow_failure_total{instance=~\"${instance}\", workflowName=~\"${workflow}\"})",
     "legendFormat": "{{workflow}}"
    }
   ]
  },
  {
   "title": "Per workflow executions",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "times" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tasks_in_workflow_count{instance=~\"${instance}\", workflowName=~\"${workflow}\"}",
     "legendFormat": "{{workflowName}}"
    }
   ]
  },
  {
   "title": "Per workflow failures",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "times" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "workflow_failure_total{instance=~\"${instance}\", workflowName=~\"${workflow}\"}",
     "legendFormat": "{{workflowName}}"
    }
   ]
  },
  {
   "title": "Mean workflow execution time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(workflow_execution_seconds_sum{instance=~\"${instance}\", workflowName=~\"${workflow}\"}/workflow_execution_seconds_count{instance=~\"${instance}\", workflowName=~\"${workflow}\"})",
     "legendFormat": "{{workflowName}}"
    }
   ]
  },
  {
   "title": "Mean workflow execution time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "(workflow_execution_seconds_max{instance=~\"${instance}\", workflowName=~\"${workflow}\"})",
     "legendFormat": "{{workflowName}}"
    }
   ]
  },
  {
   "title": "Task poll count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "times" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "task_poll_count_total", "legendFormat": "{{taskType}}" }
   ]
  },
  {
   "title": "Task mean poll frequency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "task_poll_count_total / ignoring(domain) task_poll_total",
     "legendFormat": "{{taskType}}"
    }
   ]
  }
 ]
}